$lock_cmd = hyprctl dispatch 'hl.dsp.global("quickshell:lock")'
$suspend_cmd = systemctl suspend || loginctl suspend

general {
    lock_cmd = $lock_cmd
    before_sleep_cmd = hyprctl dispatch 'hl.dsp.global("quickshell:lock")'
    after_sleep_cmd = hyprctl dispatch 'hl.dsp.global("quickshell:lockFocus")'
    inhibit_sleep = 3
}

listener {
    timeout = 300
    on-timeout = $lock_cmd
}

listener {
    timeout = 600
    on-timeout = hyprctl dispatch 'hl.dsp.dpms.off()'
    on-resume = hyprctl dispatch 'hl.dsp.dpms.on()'
}

listener {
    timeout = 900
    on-timeout = $suspend_cmd
}
