$background = 0b0e11
$onBackground = e0e6ee
$surface = 0b0e11
$surfaceDim = 0b0e11
$surfaceBright = 262d33
$surfaceContainerLowest = 000000
$surfaceContainerLow = 101418
$surfaceContainer = 151a1f
$surfaceContainerHigh = 1b2025
$surfaceContainerHighest = 20262c
$onSurface = e0e6ee
$surfaceVariant = 20262c
$onSurfaceVariant = a5acb3
$outline = 70767d
$outlineVariant = 42494f
$inverseSurface = f8f9fd
$inverseOnSurface = 535559
$shadow = 000000
$scrim = 000000
$surfaceTint = aacae9
$primary = aacae9
$primaryDim = 9cbcda
$onPrimary = 22435c
$primaryContainer = 35556f
$onPrimaryContainer = cde6ff
$inversePrimary = 42627d
$primaryFixed = bddefd
$primaryFixedDim = afd0ee
$onPrimaryFixed = 1b3d55
$onPrimaryFixedVariant = 395973
$secondary = b8c8d9
$secondaryDim = aabbcb
$onSecondary = 324250
$secondaryContainer = 2e3d4b
$onSecondaryContainer = b1c1d2
$secondaryFixed = d4e4f6
$secondaryFixedDim = c6d6e8
$onSecondaryFixed = 31414f
$onSecondaryFixedVariant = 4e5d6c
$tertiary = dedcff
$tertiaryDim = cecdfe
$onTertiary = 4b4c75
$tertiaryContainer = cecdfe
$onTertiaryContainer = 43446c
$tertiaryFixed = cecdfe
$tertiaryFixedDim = c0c0ef
$onTertiaryFixed = 2f3057
$onTertiaryFixedVariant = 4c4d75
$error = fa746f
$errorDim = c54d4a
$onError = 490006
$errorContainer = 871f21
$onErrorContainer = ff9993
$primaryPaletteKeyColor = 5a7a96
$secondaryPaletteKeyColor = 697988
$tertiaryPaletteKeyColor = 72739e
$neutralPaletteKeyColor = 75777b
$neutralVariantPaletteKeyColor = 72787f
$errorPaletteKeyColor = c84f4c
$primary_paletteKeyColor = 5a7a96
$secondary_paletteKeyColor = 697988
$tertiary_paletteKeyColor = 72739e
$neutral_paletteKeyColor = 75777b
$neutral_variant_paletteKeyColor = 72787f
$term0 = 343434
$term1 = 8383ff
$term2 = 44def5
$term3 = 75fcdd
$term4 = 82b0ce
$term5 = 8baaee
$term6 = 8ad3f1
$term7 = ccdcd6
$term8 = 9aa59f
$term9 = a29eff
$term10 = 89ecff
$term11 = c9fff3
$term12 = a9c5d5
$term13 = a8bef8
$term14 = a3e5ff
$term15 = ffffff
$rosewater = f4f0fa
$flamingo = dfe0f5
$pink = ceddff
$mauve = 98c3ff
$red = 93b2ff
$maroon = acbdf0
$peach = e0c2f9
$yellow = d0f9f4
$green = b2e8ff
$teal = bbe5ff
$sky = b6e0ff
$sapphire = 8dceff
$blue = 81c2ff
$lavender = a8d0ff
$klink = 3c8dc7
$klinkSelection = 3a8dc7
$kvisited = 3c81d9
$kvisitedSelection = 3982d9
$knegative = 607eff
$knegativeSelection = 607eff
$kneutral = c794ff
$kneutralSelection = c794ff
$kpositive = 00b7e7
$kpositiveSelection = 00b7e6
$text = e0e6ee
$subtext1 = a5acb3
$subtext0 = 70767d
$overlay2 = 62676d
$overlay1 = 53585d
$overlay0 = 45494e
$surface2 = 373b40
$surface1 = 292d31
$surface0 = 1a1d21
$base = 0b0e11
$mantle = 0b0e11
$crust = 0a0d10
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
