$primary_paletteKeyColor = 5a7e71
$secondary_paletteKeyColor = 6c7a74
$tertiary_paletteKeyColor = 9fa4c4
$neutral_paletteKeyColor = 767775
$neutral_variant_paletteKeyColor = 717975
$background = 121413
$onBackground = e2e3e0
$surface = 121413
$surfaceDim = 121413
$surfaceBright = 383a38
$surfaceContainerLowest = 0d0f0e
$surfaceContainerLow = 1a1c1b
$surfaceContainer = 1e201f
$surfaceContainerHigh = 282a29
$surfaceContainerHighest = 333534
$onSurface = e2e3e0
$surfaceVariant = 414845
$onSurfaceVariant = c1c8c4
$inverseSurface = e2e3e0
$inverseOnSurface = 2f3130
$outline = 8b928e
$outlineVariant = 414845
$shadow = 000000
$scrim = 000000
$surfaceTint = a8cfc0
$primary = a8cfc0
$onPrimary = 11362c
$primaryContainer = 88aea0
$onPrimaryContainer = 1e4237
$inversePrimary = 416559
$secondary = bbcac3
$onSecondary = 26332e
$secondaryContainer = 3c4a44
$onSecondaryContainer = a9b9b2
$tertiary = c0c5e6
$onTertiary = 292f49
$tertiaryContainer = 8a8fae
$onTertiaryContainer = 000000
$error = ffb4ab
$onError = 690005
$errorContainer = 93000a
$onErrorContainer = ffdad6
$primaryFixed = c3ebdc
$primaryFixedDim = a8cfc0
$onPrimaryFixed = 002018
$onPrimaryFixedVariant = 2a4d42
$secondaryFixed = d7e6de
$secondaryFixedDim = bbcac3
$onSecondaryFixed = 111e1a
$onSecondaryFixedVariant = 3c4a44
$tertiaryFixed = dde1ff
$tertiaryFixedDim = c0c5e6
$onTertiaryFixed = 141a33
$onTertiaryFixedVariant = 404561
$term0 = 343434
$term1 = 769e00
$term2 = 71e1a6
$term3 = 9afbb4
$term4 = 79b6a6
$term5 = 7aaee9
$term6 = 8cd9b8
$term7 = cfdcce
$term8 = 9ca59b
$term9 = 85b900
$term10 = 6cf6b1
$term11 = d3ffdb
$term12 = a6c8bb
$term13 = cec06b
$term14 = 96edc5
$term15 = ffffff
$rosewater = f1f3e5
$flamingo = e3e4c5
$pink = bae2ff
$mauve = 5bd0df
$red = c5b542
$maroon = c6c177
$peach = aadaaa
$yellow = d8f9de
$green = 98f2cb
$teal = a3eed7
$sky = 96ebd8
$sapphire = 74d8c9
$blue = 57cfc7
$lavender = 84dbd9
$klink = 00978d
$klinkSelection = 00978e
$kvisited = 008ca9
$kvisitedSelection = 008ca9
$knegative = 838f00
$knegativeSelection = 838f00
$kneutral = 34c359
$kneutralSelection = 34c359
$kpositive = 00c092
$kpositiveSelection = 00c093
$text = e2e3e0
$subtext1 = c1c8c4
$subtext0 = 8b928e
$overlay2 = 797f7c
$overlay1 = 676c69
$overlay0 = 565a58
$surface2 = 454947
$surface1 = 353836
$surface0 = 232625
$base = 121413
$mantle = 121413
$crust = 111312
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
